AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

require:
  - rubocop-performance
  - rubocop-rspec

# Disable buggy Capybara cop
Capybara/RSpec/PredicateMatcher:
  Enabled: false

# Gem-specific customizations
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*.rb'
  AllowedMethods:
    - connection

Metrics/AbcSize:
  AllowedMethods:
    - connection

Metrics/CyclomaticComplexity:
  AllowedMethods:
    - validate_get_asset_params!

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

MultipleDescribes:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*.rb'
